// All landing-page strings, in English and Hindi.
// Source of truth — don't paraphrase or fork copies into components.

export const SUPPORTED_LOCALES = ["en", "hi"];
export const DEFAULT_LOCALE = "en";

// URL segment → locale code (improvement.text §6 — /en-in/, /hi-in/).
export const LOCALE_BY_PATH = {
  "en-in": "en",
  "hi-in": "hi",
};
export const PATH_BY_LOCALE = {
  en: "en-in",
  hi: "hi-in",
};

const en = {
  navFeatures: "Features",
  navHow: "How it works",
  navPricing: "Pricing",
  navDocs: "Docs",
  signIn: "Sign in",
  signUp: "Sign up",
  login: "Login",
  cta: "git init love",

  h1a: "Find your perfect ",
  h1em: "merge conflict",
  h1b: ".",
  lede: "Merge Me is the dating app for developers. Match by stack, chat in code blocks, and ship something real together.",

  trustStrong: "24,182 developers",
  trustRest: "from 1,400 companies — and counting.",

  eyebrow1: "Recently merged into main",
  section1Title: ["Real ", "stories", ", real ", "stacks", "."],
  section1Sub:
    "Couples who actually met by matching on languages, frameworks, and the time zones they keep awake.",
  galleryFoot: "showing 6 of 1,247 — ",
  galleryFootLink: "see the rest →",
  galleryFootMeta: "~/merge-me/main · 1,247 records",

  eyebrow2: "Why it works",
  section2Title: ["Built like a ", "developer tool", ", not a slot machine."],
  section2Sub: "Three things we got right.",

  features: [
    {
      num: "01",
      titleA: "Match by ",
      titleEm: "stack",
      titleB: ", not by selfie.",
      body: "Your real overlap — languages, frameworks, time zones — drives the queue. Profiles surface why you're a fit.",
      viz: "stack",
    },
    {
      num: "02",
      titleA: "Chat in ",
      titleEm: "code blocks",
      titleB: ".",
      body: "Triple-backtick a snippet and it just works. Syntax highlight, copy button, no \"can you paste it again\".",
      viz: "chat",
    },
    {
      num: "03",
      titleA: "Real devs, ",
      titleEm: "verified",
      titleB: ".",
      body: "Link GitHub, GitLab, or Bitbucket. We check it's actually yours, then never post on your behalf.",
      viz: "verify",
    },
  ],

  ctaStripPill: "git push origin you@love",
  ctaStripTitle: ["Your team is ", "shipping ", "without you."],
  ctaStripSub: "24,000+ developers already merging. Your queue is one signup away.",

  chatThem: "got a sec? my reducer is firing twice",
  chatThemCode: "useEffect(() => fetch('/me'), [user]);",
  chatYou: "dep array. drop `user` 😉",
  chatYouCode: "// just []",

  verify: [
    ["GitHub", "@aanya-i · 4y · 218 repos"],
    ["LinkedIn", "Backend Engineer · Razorpay"],
    ["Stack Overflow", "12,400 rep · top 5% Go"],
  ],

  stackHeads: ["you", "Aanya"],
  stackList: [
    ["Go", "Kubernetes", "Postgres", "Python"],
    ["Go", "Kubernetes", "Bangalore", "Rust"],
  ],

  footerCopy: "© 2026 Merge Me Labs",
  footerStatus: "all systems operational",
  footerLinks: ["Privacy", "Terms", "Status", "Changelog"],

  swipeMerge: "Merge",
  swipePass: "Pass",
  awaiting: "$ awaiting merge…",

  // Auth pages (login + signup). Nested so they don't pollute the flat
  // landing keys — components read copy.auth.*.
  auth: {
    backToMerge: "Back to Merge Me",
    tabSignIn: "Sign in",
    tabSignUp: "Create account",

    signInTitleA: "Welcome ",
    signInTitleEm: "back",
    signInTitleB: ".",
    signInSub: "Pick up where you left off. Your queue is waiting.",

    signUpTitleA: "Make your ",
    signUpTitleEm: "dev profile",
    signUpTitleB: ".",
    signUpSub: "Two minutes to set up. Then start matching by stack, not by selfie.",

    oauthGitHub: "Continue with GitHub",
    oauthGitLab: "Continue with GitLab",
    oauthGoogle: "Continue with Google",
    divider: "or with email",

    fldFirst: "First name",
    fldFirstPh: "Aanya",
    fldLast: "Last name (optional)",
    fldLastPh: "Iyer",
    fldEmail: "Email",
    fldEmailSignUp: "Email",
    fldEmailPh: "you@company.dev",
    fldPwd: "Password",
    fldPwdPhSignIn: "your password",
    fldPwdPhSignUp: "8+ characters, 1 number",

    show: "Show",
    hide: "Hide",
    forgot: "Forgot?",
    fpTitle: "Reset your password",
    fpSub: "Enter your account email and we'll send you a reset link.",
    fpEmail: "Email",
    fpSubmit: "Send reset link",
    fpSentTitle: "Check your inbox",
    fpSentBody:
      "If an account exists for that email, we've sent a password-reset link. It expires in 15 minutes.",
    fpBack: "Back to sign in",

    rpTitle: "Choose a new password",
    rpSub: "Make it strong - you'll stay signed in on this device.",
    rpPwd: "New password",
    rpConfirm: "Confirm password",
    rpConfirmPh: "retype your password",
    rpMismatch: "Passwords do not match yet.",
    rpSubmit: "Reset password",
    rpDeadTitle: "Reset link problem",
    rpDeadBody: "This reset link is invalid or has expired.",
    rpMissing: "Missing reset token.",
    rpRequestNew: "Request a new link",
    rpResending: "Sending...",
    rpResentBody: "We sent a fresh reset link if this request is still eligible. It expires in 15 minutes.",
    rpResendInvalid: "This reset link can no longer be reused. Enter your email to request another one.",
    veTitle: "Verifying your email",
    veSub: "One moment while we activate your account on this device.",
    veErrorTitle: "Verification failed",
    veMissing: "Missing verification token.",
    veInvalid: "Verification link is invalid or expired.",

    pwd0: "use 8+ chars, mixed case + number",
    pwd1: "weak",
    pwd2: "okay",
    pwd3: "good",
    pwd4: "strong",

    submitSignIn: "Sign in",
    submitSignUp: "git init love",

    footSignIn: "New here? ",
    footSignInLink: "Create an account",
    footSignUp: "Already shipping? ",
    footSignUpLink: "Sign in",

    legalA: "By continuing, you agree to our ",
    legalTerms: "Terms",
    legalAnd: " and acknowledge our ",
    legalPrivacy: "Privacy Policy",
    legalEnd: ".",

    livePill: "live · 12 devs swiping right now",

    showcase: [
      {
        quote: ["We resolved our ", "merge conflicts", " in Lisbon. Two months later, we're shipping a startup together."],
        who: "Diego × Sasha",
        meta: "merged 09/25 · go + ts · ✓ verified",
        photo: "/landing/auth-showcase.png",
        avatar: "/landing/g8-7.png",
        tags: ["go × ts", "amsterdam", "merged 09/25"],
      },
      {
        quote: ["Our first chat was a ", "stack trace", ". Our first date was a refactor."],
        who: "Ada × Theo",
        meta: "merged 05/25 · rust + embedded · ✓ verified",
        photo: "/landing/auth-showcase.png",
        avatar: "/landing/g8-1.png",
        tags: ["rust × c", "oakland", "long-running"],
      },
      {
        quote: ["He pushed to ", "main", ". I held the line. Now we deploy together every Friday."],
        who: "Marco × Zoé",
        meta: "merged 02/26 · go + python · ✓ verified",
        photo: "/landing/auth-showcase.png",
        avatar: "/landing/g8-3.png",
        tags: ["go × py", "istanbul", "v2.0 shipped"],
      },
    ],
  },

  // Logged-in app pages — sidebar, topbar, and the four main pages.
  // Strings copied verbatim from the design handoff.
  app: {
    nav: {
      product: "PRODUCT",
      personal: "PERSONAL",
      feed: "Feed",
      connections: "Connections",
      requests: "Requests",
      profile: "Profile",
      premium: "Premium",
      help: "Help",
      logout: "Sign out",
    },
    topbar: {
      pathPrefix: "~/merge-me",
      searchPh: "Search profiles, skills, locations…",
    },
    feed: {
      eyebrow: "Your queue · ranked by stack overlap",
      titleA: "Today's ",
      titleEm: "Create Pull Requests",
      titleB: ".",
      sub: "5 in the queue · refreshes every 6 hours.",
      whyTitle: "Why we surfaced this profile",
      whyShared: "Shared stack",
      whyDistance: "Distance",
      whyTimezone: "Timezone delta",
      whyVerified: "Verified",
      whyRepos: "Public repos",
      whyOnline: "Active now",
      whyOffline: "Last seen recently",
      todayUsed: "Used today",
      todayLeft: " left",
      pass: "Pass",
      merge: "Merge",
      bookmark: "Bookmark",
      passKb: "←",
      mergeKb: "→",
      awaiting: "$ awaiting input · ←/→/space",
      emptyTitle: "Queue is empty",
      emptySub: "Come back in 6 hours, or expand your radius in settings.",
      rankedBy: "ranked by overlap",
      refresh: "~6h refresh",
      profileCount: "profile",
      quota: "Quota",
    },
    connections: {
      eyebrow: "Active merges",
      titleA: "Your ",
      titleEm: "main",
      titleB: ".",
      sub: "6 active conversations · 3 unread.",
      filterAll: "All",
      filterUnread: "Unread",
      filterOnline: "Online",
      filterRecent: "Recent",
      lastSeenOn: "online",
      composer: "Type a message · ``` for code blocks",
      send: "Send",
      empty: "Pick a conversation to open it.",
      unmerge: "Unmerge",
      block: "Block",
      report: "Report",
      shared: "shared",
      today: "— today —",
      codeHint: "``` for code",
    },
    requests: {
      titleA: "Your ",
      titleEm: "review queue",
      titleB: ".",
      sub: "Review and accept or reject. They'll only know if you accept.",
      accept: "Accept",
      reject: "Reject",
      emptyTitle: "You're all caught up.",
      emptySub: "No pending requests. Go ship something.",
    },
    profile: {
      eyebrow: "Your profile · visible to matched devs",
      titleA: "Hi, ",
      titleEm: "there",
      titleB: ".",
      sub: "This is what other developers see. Keep it sharp.",
      edit: "Edit profile",
      save: "Save changes",
      saving: "Saving…",
      cancel: "Cancel",
      sectionAbout: "About",
      sectionSkills: "Skills",
      sectionLinks: "Links",
      sectionDetails: "Details",
      linkPlaceholder: "Profile URL",
      emptyLinks: "No links added yet.",
      addSkill: "Add",
      skillPlaceholder: "Add a skill and press Enter",
      maxSkills: "Up to {n} skills.",
      avatarPlaceholder: "…or paste an image URL",
      avatarUpload: "Upload photo",
      avatarRemove: "Remove photo",
      avatarInvalid: "Please choose a valid image file.",
      avatarTooBig: "Image is too large. Try a smaller one.",
      labelFirst: "First name",
      labelLast: "Last name",
      labelEmail: "Email",
      labelAge: "Age",
      labelGender: "Gender",
      genderUnset: "Not set",
      membership: "Membership",
      premium: "Premium",
      free: "Free",
      emptyAbout: "No bio yet.",
      emptySkills: "No skills added yet.",
    },
    premium: {
      eyebrow: "git push --force · upgrade",
      titleA: "Match more, ",
      titleEm: "merge faster",
      titleB: ".",
      sub: "Three plans · cancel anytime · no credit card to start free.",
      billingMonthly: "Monthly",
      billingAnnual: "Annual",
      annualNote: "save 25%",
      perMonth: "/ mo",
      perMonthBilled: "billed monthly",
      perMonthAnnual: "billed annually",
      mostPopular: "most popular",
      ctaFree: "Current plan",
      ctaPro: "Upgrade to Pro",
      ctaTeam: "Start Team-of-2",
      faqEyebrow: "FAQ",
      faqTitleA: "Frequently ",
      faqTitleEm: "asked",
      faqTitleB: ".",
      receiptsEyebrow: "Receipts",
      receiptsTitle: "Billing history",
      receiptsEmpty: "No charges yet. You're on the free plan.",
      receiptsCols: ["item", "when", "amount", "status"],
      receiptsAll: "View all invoices →",
      legalA: "Prices in USD. ",
      legalTerms: "Billing terms",
      legalAnd: " · ",
      legalRefund: "Refund policy",
      alreadyPremium: "You're already on a premium plan. Manage in Settings.",
    },
    help: {
      articlesH: "Popular articles",
      faqH: "Frequently asked",
      contactH: "Still stuck?",
      contactSub: "Reach us any time — we reply within 4 hours on weekdays.",
      contactCta: "Email us",
    },
  },
};

const hi = {
  navFeatures: "फ़ीचर्स",
  navHow: "कैसे काम करता है",
  navPricing: "प्राइसिंग",
  navDocs: "डॉक्स",
  signIn: "साइन इन",
  signUp: "साइन अप",
  login: "लॉगिन",
  cta: "git init love",

  h1a: "अपना परफेक्ट ",
  h1em: "merge conflict",
  h1b: " ढूंढो।",
  lede: "मर्ज मी डेवलपर्स के लिए डेटिंग ऐप है। स्टैक पर मैच करो, कोड ब्लॉक में चैट करो, और साथ मिलकर कुछ असली शिप करो।",

  trustStrong: "24,182 डेवलपर्स",
  trustRest: "1,400 कंपनियों से — और बढ़ रहे हैं।",

  eyebrow1: "हाल ही में main में मर्ज हुए",
  section1Title: ["असली ", "कहानियाँ", ", असली ", "स्टैक", "।"],
  section1Sub:
    "जो जोड़े सच में मिले — लैंग्वेज, फ्रेमवर्क, और जिन टाइमज़ोन्स में जागते हैं उन पर मैच करके।",
  galleryFoot: "1,247 में से 6 दिख रहे — ",
  galleryFootLink: "बाकी देखें →",
  galleryFootMeta: "~/merge-me/main · 1,247 records",

  eyebrow2: "क्यों चलता है",
  section2Title: ["स्लॉट मशीन नहीं — ", "डेवलपर टूल", " की तरह बना है।"],
  section2Sub: "तीन चीज़ें जो हमने सही कीं।",

  features: [
    {
      num: "01",
      titleA: "सेल्फी नहीं, ",
      titleEm: "स्टैक",
      titleB: " से मैच।",
      body: "लैंग्वेज, फ्रेमवर्क, टाइमज़ोन — आपका असली ओवरलैप ही क्यू तय करता है। प्रोफ़ाइल बताती है कि क्यों फिट हो।",
      viz: "stack",
    },
    {
      num: "02",
      titleA: "",
      titleEm: "कोड ब्लॉक",
      titleB: " में चैट करो।",
      body: "ट्रिपल-बैकटिक से स्निपेट डालो, बस हो गया। सिंटैक्स हाइलाइट, कॉपी बटन, बिना \"फिर से भेजो\"।",
      viz: "chat",
    },
    {
      num: "03",
      titleA: "असली डेवलपर्स, ",
      titleEm: "वेरिफ़ाइड",
      titleB: "।",
      body: "GitHub, GitLab या Bitbucket जोड़ो। हम देखते हैं कि असली में आपका है, और कभी आपकी तरफ़ से पोस्ट नहीं करते।",
      viz: "verify",
    },
  ],

  ctaStripPill: "git push origin you@love",
  ctaStripTitle: ["आपकी टीम आपके बिना ", "शिप", " कर रही है।"],
  ctaStripSub: "24,000+ डेवलपर्स पहले से मर्ज कर रहे हैं। एक साइन-अप दूर।",

  chatThem: "एक सेकंड? मेरा reducer दो बार चल रहा है",
  chatThemCode: "useEffect(() => fetch('/me'), [user]);",
  chatYou: "dep array. `user` हटा दो 😉",
  chatYouCode: "// बस []",

  verify: [
    ["GitHub", "@aanya-i · 4 साल · 218 repos"],
    ["LinkedIn", "बैकएंड इंजी. · Razorpay"],
    ["Stack Overflow", "12,400 rep · top 5% Go"],
  ],

  stackHeads: ["आप", "आन्या"],
  stackList: [
    ["Go", "Kubernetes", "Postgres", "Python"],
    ["Go", "Kubernetes", "बेंगलुरु", "Rust"],
  ],

  footerCopy: "© 2026 मर्ज मी लैब्स",
  footerStatus: "सब सिस्टम चालू",
  footerLinks: ["प्राइवेसी", "टर्म्स", "स्टेटस", "चेंजलॉग"],

  swipeMerge: "मर्ज",
  swipePass: "पास",
  awaiting: "$ awaiting merge…",

  auth: {
    backToMerge: "मर्ज मी पर वापस",
    navStatus: "v1.0 · पब्लिक बीटा",
    tabSignIn: "साइन इन",
    tabSignUp: "अकाउंट बनाएँ",

    signInTitleA: "वापसी पर ",
    signInTitleEm: "स्वागत",
    signInTitleB: " है।",
    signInSub: "जहाँ छोड़ा था वहीं से शुरू करें। आपका क्यू इंतज़ार में है।",

    signUpTitleA: "अपनी ",
    signUpTitleEm: "डेव प्रोफ़ाइल",
    signUpTitleB: " बनाएँ।",
    signUpSub: "दो मिनट में सेट करें। फिर सेल्फी नहीं — स्टैक से मैच करें।",

    oauthGitHub: "GitHub से जारी रखें",
    oauthGitLab: "GitLab से जारी रखें",
    oauthGoogle: "Google से जारी रखें",
    divider: "या ईमेल से",

    fldFirst: "पहला नाम",
    fldFirstPh: "आन्या",
    fldLast: "उपनाम (वैकल्पिक)",
    fldLastPh: "अय्यर",
    fldEmail: "ईमेल या उपयोगकर्ता नाम",
    fldEmailSignUp: "ईमेल",
    fldEmailPh: "you@company.dev",
    fldPwd: "पासवर्ड",
    fldPwdPhSignIn: "आपका पासवर्ड",
    fldPwdPhSignUp: "8+ अक्षर, 1 नंबर",

    show: "दिखाएँ",
    hide: "छुपाएँ",
    forgot: "भूल गए?",
    fpTitle: "पासवर्ड रीसेट करें",
    fpSub: "अपना अकाउंट ईमेल डालें, हम आपको रीसेट लिंक भेजेंगे।",
    fpEmail: "ईमेल",
    fpSubmit: "रीसेट लिंक भेजें",
    fpSentTitle: "अपना इनबॉक्स देखें",
    fpSentBody:
      "अगर उस ईमेल से कोई अकाउंट है, तो हमने पासवर्ड-रीसेट लिंक भेज दिया है। यह 15 मिनट में समाप्त हो जाएगा।",
    fpBack: "साइन इन पर वापस जाएँ",

    rpTitle: "नया पासवर्ड चुनें",
    rpSub: "मज़बूत पासवर्ड रखें — आप इस डिवाइस पर साइन इन रहेंगे।",
    rpPwd: "नया पासवर्ड",
    rpConfirm: "पासवर्ड फिर से लिखें",
    rpConfirmPh: "अपना पासवर्ड दोबारा लिखें",
    rpMismatch: "दोनों पासवर्ड अभी मेल नहीं खा रहे हैं।",
    rpSubmit: "पासवर्ड रीसेट करें",
    rpDeadTitle: "रीसेट लिंक में समस्या",
    rpDeadBody: "यह रीसेट लिंक अमान्य है या समाप्त हो चुका है।",
    rpMissing: "रीसेट टोकन मौजूद नहीं है।",
    rpRequestNew: "नया लिंक माँगें",
    rpResending: "भेजा जा रहा है...",
    rpResentBody: "अगर यह अनुरोध अभी भी मान्य है, तो हमने नया रीसेट लिंक भेज दिया है। यह 15 मिनट में समाप्त हो जाएगा।",
    rpResendInvalid: "यह रीसेट लिंक अब दोबारा इस्तेमाल नहीं हो सकता। नया लिंक पाने के लिए अपना ईमेल दर्ज करें।",
    veTitle: "आपका ईमेल सत्यापित किया जा रहा है",
    veSub: "एक क्षण दें, हम इस डिवाइस पर आपका अकाउंट सक्रिय कर रहे हैं।",
    veErrorTitle: "सत्यापन विफल हुआ",
    veMissing: "सत्यापन टोकन मौजूद नहीं है।",
    veInvalid: "यह सत्यापन लिंक अमान्य है या समाप्त हो चुका है।",

    pwd0: "8+ अक्षर, बड़े-छोटे + नंबर का इस्तेमाल करें",
    pwd1: "कमज़ोर",
    pwd2: "ठीक",
    pwd3: "अच्छा",
    pwd4: "मज़बूत",

    submitSignIn: "साइन इन",
    submitSignUp: "git init love",

    footSignIn: "नए हैं? ",
    footSignInLink: "अकाउंट बनाएँ",
    footSignUp: "पहले से शिप कर रहे हैं? ",
    footSignUpLink: "साइन इन",

    legalA: "जारी रखते हुए, आप हमारी ",
    legalTerms: "टर्म्स",
    legalAnd: " से सहमत हैं और हमारी ",
    legalPrivacy: "प्राइवेसी पॉलिसी",
    legalEnd: " स्वीकार करते हैं।",

    livePill: "live · अभी 12 डेव स्वाइप कर रहे हैं",

    showcase: [
      {
        quote: ["हमने अपने ", "merge conflicts", " लिस्बन में सुलझाए। दो महीने बाद, हम एक स्टार्टअप शिप कर रहे हैं।"],
        who: "दिएगो × साशा",
        meta: "merged 09/25 · go + ts · ✓ verified",
        photo: "/landing/auth-showcase.png",
        avatar: "/landing/g8-7.png",
        tags: ["go × ts", "amsterdam", "merged 09/25"],
      },
      {
        quote: ["हमारी पहली बातचीत एक ", "stack trace", " थी। पहला डेट एक refactor था।"],
        who: "एडा × थिओ",
        meta: "merged 05/25 · rust + embedded · ✓ verified",
        photo: "/landing/auth-showcase.png",
        avatar: "/landing/g8-1.png",
        tags: ["rust × c", "oakland", "long-running"],
      },
      {
        quote: ["उसने ", "main", " पर पुश किया। मैंने लाइन होल्ड की। अब हम हर शुक्रवार साथ डिप्लॉय करते हैं।"],
        who: "मार्को × ज़ोए",
        meta: "merged 02/26 · go + python · ✓ verified",
        photo: "/landing/auth-showcase.png",
        avatar: "/landing/g8-3.png",
        tags: ["go × py", "istanbul", "v2.0 shipped"],
      },
    ],
  },

  app: {
    nav: {
      product: "प्रोडक्ट",
      personal: "पर्सनल",
      feed: "फ़ीड",
      connections: "कनेक्शन",
      requests: "रिक्वेस्ट्स",
      profile: "प्रोफ़ाइल",
      premium: "प्रीमियम",
      help: "मदद",
      logout: "साइन आउट",
    },
    topbar: {
      pathPrefix: "~/merge-me",
      searchPh: "प्रोफ़ाइल, स्किल, जगह खोजें…",
    },
    feed: {
      eyebrow: "आपका क्यू · स्टैक ओवरलैप से रैंक्ड",
      titleA: "आज के ",
      titleEm: "उम्मीदवार",
      titleB: "।",
      sub: "क्यू में 5 · हर 6 घंटे में रिफ्रेश।",
      whyTitle: "हमने यह प्रोफ़ाइल क्यों दिखाई",
      whyShared: "साझा स्टैक",
      whyDistance: "दूरी",
      whyTimezone: "टाइमज़ोन अंतर",
      whyVerified: "वेरिफ़ाइड",
      whyRepos: "पब्लिक repos",
      whyOnline: "अभी सक्रिय",
      whyOffline: "हाल में देखा",
      todayUsed: "आज इस्तेमाल",
      todayLeft: " बाकी",
      pass: "पास",
      merge: "मर्ज",
      bookmark: "बुकमार्क",
      passKb: "←",
      mergeKb: "→",
      awaiting: "$ इनपुट का इंतज़ार · ←/→/space",
      emptyTitle: "क्यू ख़ाली है",
      emptySub: "6 घंटे बाद आएँ, या सेटिंग्स में रेडियस बढ़ाएँ।",
      rankedBy: "ओवरलैप से रैंक्ड",
      refresh: "~6h रिफ्रेश",
      profileCount: "प्रोफ़ाइल",
      quota: "कोटा",
    },
    connections: {
      eyebrow: "एक्टिव मर्ज",
      titleA: "आपका ",
      titleEm: "main",
      titleB: "।",
      sub: "6 एक्टिव बातचीत · 3 अनरीड।",
      filterAll: "सभी",
      filterUnread: "अनरीड",
      filterOnline: "ऑनलाइन",
      filterRecent: "नए",
      lastSeenOn: "ऑनलाइन",
      composer: "मैसेज लिखें · कोड के लिए ``` लगाएँ",
      send: "भेजें",
      empty: "खोलने के लिए कोई बातचीत चुनें।",
      unmerge: "अनमर्ज",
      block: "ब्लॉक",
      report: "रिपोर्ट",
      shared: "साझा",
      today: "— आज —",
      codeHint: "कोड के लिए ```",
    },
    requests: {
      eyebrow: "इनकमिंग · 5 लोग आपसे मर्ज करना चाहते हैं",
      titleA: "आपकी ",
      titleEm: "रिव्यू क्यू",
      titleB: "।",
      sub: "रिव्यू करके स्वीकार या अस्वीकार करें। अस्वीकार की जानकारी उन्हें नहीं मिलती।",
      whyInterested: "क्यों वे इच्छुक हैं",
      shared: "साझा स्टैक",
      accept: "स्वीकार",
      reject: "अस्वीकार",
      seeMore: "पूरी प्रोफ़ाइल",
      sentNote: "नोट के साथ:",
      sent: "भेजा",
      emptyTitle: "सब निपटा लिया।",
      emptySub: "कोई रिक्वेस्ट बाकी नहीं। जाकर कुछ शिप करो।",
    },
    profile: {
      eyebrow: "आपकी प्रोफ़ाइल · केवल मैच किए डेव देखते हैं",
      titleA: "नमस्ते, ",
      titleEm: "डेव",
      titleB: "।",
      sub: "यही दूसरे डेवलपर देखते हैं। इसे बेहतरीन बनाए रखें।",
      edit: "प्रोफ़ाइल संपादित करें",
      save: "बदलाव सहेजें",
      saving: "सहेजा जा रहा है…",
      cancel: "रद्द करें",
      sectionAbout: "अपने बारे में",
      sectionSkills: "स्किल्स",
      sectionLinks: "लिंक",
      sectionDetails: "विवरण",
      linkPlaceholder: "प्रोफ़ाइल URL",
      emptyLinks: "अभी कोई लिंक नहीं जोड़ी।",
      addSkill: "जोड़ें",
      skillPlaceholder: "स्किल लिखें और Enter दबाएँ",
      maxSkills: "अधिकतम {n} स्किल्स।",
      avatarPlaceholder: "…या इमेज URL पेस्ट करें",
      avatarUpload: "फ़ोटो अपलोड करें",
      avatarRemove: "फ़ोटो हटाएँ",
      avatarInvalid: "कृपया एक मान्य इमेज फ़ाइल चुनें।",
      avatarTooBig: "इमेज बहुत बड़ी है। छोटी इमेज चुनें।",
      labelFirst: "पहला नाम",
      labelLast: "अंतिम नाम",
      labelEmail: "ईमेल",
      labelAge: "उम्र",
      labelGender: "लिंग",
      genderUnset: "तय नहीं",
      membership: "सदस्यता",
      premium: "प्रीमियम",
      free: "फ़्री",
      emptyAbout: "अभी कोई बायो नहीं।",
      emptySkills: "अभी कोई स्किल नहीं जोड़ी।",
    },
    premium: {
      eyebrow: "git push --force · अपग्रेड",
      titleA: "ज़्यादा मैच, ",
      titleEm: "तेज़ मर्ज",
      titleB: "।",
      sub: "तीन प्लान · कभी भी रद्द · फ़्री शुरू करने के लिए क्रेडिट कार्ड ज़रूरी नहीं।",
      billingMonthly: "मासिक",
      billingAnnual: "वार्षिक",
      annualNote: "25% बचत",
      perMonth: "/ माह",
      perMonthBilled: "मासिक बिलिंग",
      perMonthAnnual: "वार्षिक बिलिंग",
      mostPopular: "सबसे लोकप्रिय",
      ctaFree: "मौजूदा प्लान",
      ctaPro: "प्रो में अपग्रेड करें",
      ctaTeam: "Team-of-2 शुरू करें",
      faqEyebrow: "FAQ",
      faqTitleA: "अक्सर पूछे ",
      faqTitleEm: "जाने वाले",
      faqTitleB: "।",
      receiptsEyebrow: "रसीदें",
      receiptsTitle: "बिलिंग इतिहास",
      receiptsEmpty: "अभी कोई चार्ज नहीं। आप फ़्री प्लान पर हैं।",
      receiptsCols: ["आइटम", "कब", "रक़म", "स्थिति"],
      receiptsAll: "सभी इनवॉइस देखें →",
      legalA: "कीमतें USD में। ",
      legalTerms: "बिलिंग शर्तें",
      legalAnd: " · ",
      legalRefund: "रिफंड नीति",
      alreadyPremium: "आप पहले से ही प्रीमियम पर हैं। सेटिंग्स में मैनेज करें।",
    },
    help: {
      articlesH: "लोकप्रिय आर्टिकल",
      faqH: "अक्सर पूछे जाने वाले",
      contactH: "अभी भी अटके हैं?",
      contactSub: "किसी भी समय संपर्क करें — वीकडेज़ में हम 4 घंटे के अंदर जवाब देते हैं।",
      contactCta: "ईमेल करें",
    },
  },
};

export const COPY = { en, hi };

export const getCopy = (locale) => COPY[locale] || COPY[DEFAULT_LOCALE];
